apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "keycloak.annotations" . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- $annotations := merge .Values.podAnnotations .Values.commonAnnotations }}
      {{- with $annotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "keycloak.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "keycloak.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- with (include "keycloak.imagePullSecrets" .) }}
{{- . | nindent 6 }}
{{- end }}
      securityContext: {{ include "cloudpirates.renderPodSecurityContext" . | nindent 8 }}
      initContainers:
        - name: copy-quarkus-lib
          securityContext: {{ include "cloudpirates.renderContainerSecurityContext" . | nindent 12 }}
          image: {{ include "keycloak.image" . }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          command: ["sh", "-c", "cp -r /opt/keycloak/lib/quarkus/* /shared-quarkus/"]
          volumeMounts:
            - name: keycloak-lib-quarkus
              mountPath: /shared-quarkus
        {{- if .Values.postgres.enabled }}
        - name: wait-for-postgres
          securityContext: {{ include "cloudpirates.renderContainerSecurityContext" . | nindent 12 }}
          image: {{ .Values.initContainers.waitForPostgres.image }}
          command: ["sh", "-c", "until pg_isready -h {{ .Release.Name }}-postgres -p 5432 -U postgres; do echo waiting for database; sleep 2; done;"]
        {{- else if .Values.mariadb.enabled }}
        - name: wait-for-mariadb
          securityContext: {{ include "cloudpirates.renderContainerSecurityContext" . | nindent 12 }}
          image: {{ .Values.initContainers.waitForMariadb.image }}
          command: ["sh", "-c", "until mysqladmin ping -h {{ .Release.Name }}-mariadb -P 3306 --silent; do echo waiting for database; sleep 2; done;"]
        {{- end }}
        {{- if .Values.extraInitContainers }}
          {{- toYaml .Values.extraInitContainers | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext: {{ include "cloudpirates.renderContainerSecurityContext" . | nindent 12 }}
          image: {{ include "keycloak.image" . }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          command:
            - {{ .Values.image.command }}
          args:
            {{- if .Values.keycloak.production }}
            - start
            {{- else }}
            - start-dev
            {{- if .Values.realm.import }}
            - --import-realm
            {{- end }}
            {{- end }}
            {{- if .Values.keycloak.httpEnabled }}
            - --http-enabled=true
            {{- end }}
            {{- if .Values.keycloak.hostname }}
            - --hostname={{ include "keycloak.hostname" . }}
            {{- end }}
            {{- if .Values.keycloak.hostnameAdmin }}
            - --hostname-admin={{ include "keycloak.hostnameAdmin" . }}
            {{- end }}
            - --hostname-strict={{ .Values.keycloak.hostnameStrict }}
            {{- if .Values.keycloak.hostnameBackchannel }}
            - --hostname-backchannel={{ include "keycloak.hostnameBackchannel" . }}
            {{- end }}
            {{- if .Values.keycloak.proxyHeaders }}
            - --proxy-headers={{ .Values.keycloak.proxyHeaders }}
            {{- end }}
            {{- if .Values.keycloak.proxyProtocolEnabled }}
            - --proxy-protocol-enabled={{ .Values.keycloak.proxyProtocolEnabled }}
            {{- end }}
            {{- if .Values.keycloak.proxyTrustedAddresses }}
            - --proxy-trusted-addresses={{ .Values.keycloak.proxyTrustedAddresses }}
            {{- end }}
            {{- if .Values.keycloak.httpPort }}
            - --http-port={{ .Values.keycloak.httpPort }}
            {{- end }}
            {{- if .Values.keycloak.httpsPort }}
            - --https-port={{ .Values.keycloak.httpsPort }}
            {{- end }}
            {{- if not (has .Values.database.type (list "h2-file" "h2-mem" "dev-mem")) }}
            - --db={{ .Values.database.type }}
            - --db-url={{ include "keycloak.databaseUrl" . }}
            {{- end }}
            {{- if ne .Values.cache.stack "local" }}
            - --cache={{ .Values.cache.stack }}
            {{- end }}
            {{- if .Values.features.enabled }}
            - --features={{ join "," .Values.features.enabled }}
            {{- end }}
            {{- if .Values.features.disabled }}
            - --features-disabled={{ join "," .Values.features.disabled }}
            {{- end }}
            {{- if .Values.metrics.enabled }}
            - --metrics-enabled=true
            {{- end }}
            {{- with .Values.keycloak.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.tls.enabled }}
            - --https-certificate-file={{ .Values.tls.certificateFile }}
            - --https-certificate-key-file={{ .Values.tls.certificateKeyFile }}
            {{- end }}
            {{- if .Values.tls.truststoreEnabled }}
            - --https-trust-store-file={{ .Values.tls.truststoreFile }}
            {{- if .Values.tls.truststorePassword }}
            - --https-trust-store-password={{ .Values.tls.truststorePassword }}
            {{- end }}
            {{- end }}
          env:
            - name: KC_HTTP_RELATIVE_PATH
              value: {{ .Values.keycloak.httpRelativePath | quote | default "/" }}
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: {{ .Values.keycloak.adminUser | quote }}
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "keycloak.secretName" . }}
                  key: {{ include "keycloak.adminPasswordKey" . }}
            {{- if or (eq .Values.database.type "postgres") (eq .Values.database.type "mysql") (eq .Values.database.type "mariadb") }}
            - name: KC_DB_USERNAME
              {{- if and (eq .Values.database.type "postgres") .Values.postgres.enabled }}
              value: {{ default "postgres" .Values.postgres.auth.username | quote }}
              {{- else if and (or (eq .Values.database.type "mysql") (eq .Values.database.type "mariadb")) .Values.mariadb.enabled }}
              value: {{ default "root" .Values.mariadb.auth.username | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "keycloak.databaseSecretName" . }}
                  key: {{ include "keycloak.databaseUsernameKey" . }}
              {{- end }}
            - name: KC_DB_PASSWORD
              {{- if and (eq .Values.database.type "postgres") .Values.postgres.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres
                  key: postgres-password
              {{- else if and (or (eq .Values.database.type "mysql") (eq .Values.database.type "mariadb")) .Values.mariadb.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mariadb
                  key: {{ if .Values.mariadb.auth.username }}mariadb-password{{ else }}mariadb-root-password{{ end }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "keycloak.databaseSecretName" . }}
                  key: {{ include "keycloak.databasePasswordKey" . }}
              {{- end }}
            {{- end }}
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if .Values.extraEnvVarsSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.extraEnvVarsSecret }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.keycloak.httpPort }}
              protocol: TCP
            {{- if and .Values.keycloak.httpsPort (not .Values.keycloak.httpEnabled) }}
            - name: https
              containerPort: {{ .Values.keycloak.httpsPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.metrics.enabled }}
            - name: http-metrics
              containerPort: {{ .Values.metrics.service.port }}
              protocol: TCP
            {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ include "keycloak.probeUrl" . }}
              port: http
              scheme: HTTP
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ include "keycloak.probeUrl" . }}
              port: http
              scheme: HTTP
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ include "keycloak.probeUrl" . }}
              port: http
              scheme: HTTP
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /opt/keycloak/data
            {{- if .Values.cache.configFile }}
            - name: cache-config
              mountPath: /opt/keycloak/conf/cache-ispn.xml
              subPath: cache-ispn.xml
              readOnly: true
            {{- end }}
            - name: tmp
              mountPath: /tmp
            - name: keycloak-work
              mountPath: /opt/keycloak/work
            - name: keycloak-lib-quarkus
              mountPath: /opt/keycloak/lib/quarkus
            {{- if .Values.realm.import }}
            - name: realm-config
              mountPath: /opt/keycloak/data/import
              readOnly: true
            {{- end }}
            {{- if .Values.tls.enabled }}
            - name: tls-certs
              mountPath: /opt/keycloak/certs
              readOnly: true
            {{- end }}
            {{- if .Values.tls.truststoreEnabled }}
            - name: tls-truststore
              mountPath: /opt/keycloak/truststore
              readOnly: true
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
              {{- toYaml .Values.extraVolumeMounts | nindent 12}}
            {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ default (include "keycloak.fullname" .) .Values.persistence.existingClaim }}
        {{- else }}
        - name: data
          emptyDir: {}
        {{- end }}
        {{- if .Values.cache.configFile }}
        - name: cache-config
          configMap:
            name: {{ include "keycloak.fullname" . }}-cache
        {{- end }}
        - name: tmp
          emptyDir: {}
        - name: keycloak-work
          emptyDir: {}
        - name: keycloak-lib-quarkus
          emptyDir: {}
        {{- if .Values.realm.import }}
        - name: realm-config
          configMap:
            name: {{ include "keycloak.fullname" . }}-realm
        {{- end }}
        {{- if .Values.tls.enabled }}
        - name: tls-certs
          secret:
            secretName: {{ include "keycloak.tlsSecretName" . }}
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
        {{- end }}
        {{- if .Values.tls.truststoreEnabled }}
        - name: tls-truststore
          secret:
            secretName: {{ .Values.tls.truststoreExistingSecret }}
            items:
              - key: truststore.jks
                path: truststore.jks
        {{- end }}
        {{- if .Values.extraVolumes }}
          {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
