apiVersion: v2
name: mariadb
description: MariaDB is a high-performance, open-source relational database server that is a drop-in replacement for MySQL. Supports both single-node and Galera Cluster deployments.
type: application
version: 0.5.4
appVersion: "12.0.2"
keywords:
  - mariadb
  - mysql
  - database
  - sql
  - relational
  - galera
  - cluster
  - replication
home: https://mariadb.org
sources:
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/mariadb
  - https://github.com/MariaDB/server
  - https://github.com/MariaDB/mariadb-docker
maintainers:
  - name: CloudPirates GmbH & Co. KG
    email: hello@cloudpirates.io
    url: https://www.cloudpirates.io
  - name: Gianni Carafa
    email: gianni.carafa@srf.ch
    url: https://www.srf.ch
dependencies:
  - name: common
    version: "2.x.x"
    repository: oci://registry-1.docker.io/cloudpirates
icon: https://a.storyblok.com/f/143071/512x512/6512dd22ee/mariadb-logo.svg
annotations:
  license: Apache-2.0
  artifacthub.io/category: database
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/signKey: |
    fingerprint: 6917f1a88c122cbb1de5aa55457752135bdcf95a
    url: https://raw.githubusercontent.com/CloudPirates-io/helm-charts/refs/heads/main/cosign.pub
  artifacthub.io/links: |
    - name: MariaDB
      url: https://mariadb.org
    - name: Helm Chart
      url: https://github.com/CloudPirates-io/helm-charts/tree/main/charts/mariadb
    - name: Application
      url: https://github.com/MariaDB/server
    - name: Docker Image
      url: https://github.com/MariaDB/mariadb-docker
    - name: Galera Cluster
      url: https://galeracluster.com
    - name: Maintainer CloudPirates
      url: https://www.cloudpirates.io
  artifacthub.io/changes: |2
        - kind: changed
          description: "make mariadb run on openshift (#176)"
          links:
            - name: "Commit e2c3afb"
              url: "https://github.com/dloewen2/helm-charts/commit/e2c3afb"
