apiVersion: v2
name: mariadb
description: MariaDB is a high-performance, open-source relational database server that is a drop-in replacement for MySQL. Supports both single-node and Galera Cluster deployments.
type: application
version: 0.5.0
appVersion: "12.0.2"
keywords:
  - mariadb
  - mysql
  - database
  - sql
  - relational
  - galera
  - cluster
  - replication
home: https://www.cloudpirates.io

sources:
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/mariadb

maintainers:
  - name: CloudPirates GmbH & Co. KG
    url: https://www.cloudpirates.io

dependencies:
  - name: common
    version: "2.x.x"
    repository: oci://registry-1.docker.io/cloudpirates

icon: https://a.storyblok.com/f/143071/512x512/6512dd22ee/mariadb-logo.svg
