apiVersion: v2
name: ghost
description: A simple, powerful publishing platform that allows you to share your stories with the world.
type: application
version: 0.3.4
appVersion: "6.4.0"
keywords:
  - ghost
  - blogging
  - content management
home: https://ghost.org
sources:
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/ghost
  - https://github.com/TryGhost/Ghost
maintainers:
  - name: CloudPirates GmbH & Co. KG
    email: hello@cloudpirates.io
    url: https://www.cloudpirates.io
  - name: Gianni Carafa
    email: gianni.carafa@srf.ch
    url: https://www.srf.ch
dependencies:
  - name: common
    version: "2.x.x"
    repository: oci://registry-1.docker.io/cloudpirates
  - name: mariadb
    version: "0.4.x"
    repository: oci://registry-1.docker.io/cloudpirates
    condition: mariadb.enabled
icon: https://a.storyblok.com/f/143071/512x512/3a5c1cb0c5/ghost-logo.png
annotations:
  license: Apache-2.0
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/signKey: |
    fingerprint: 6917f1a88c122cbb1de5aa55457752135bdcf95a
    url: https://raw.githubusercontent.com/CloudPirates-io/helm-charts/refs/heads/main/cosign.pub
  artifacthub.io/links: |
    - name: Ghost
      url: https://ghost.org
    - name: Helm Chart
      url: https://github.com/CloudPirates-io/helm-charts/tree/main/charts/ghost
    - name: Application
      url: https://github.com/TryGhost/Ghost
    - name: Maintainer CloudPirates
      url: https://www.cloudpirates.io
  artifacthub.io/changes: |2
        - kind: changed
          description: "Update charts/ghost/values.yaml ghost (#447)"
          links:
            - name: "Commit 881ef3b"
              url: "https://github.com/CloudPirates-io/helm-charts/commit/881ef3b"
