apiVersion: v2
name: memcached
description: Memcached is an in-memory key-value store for small chunks of arbitrary data (strings, objects) from results of database calls, API calls, or page rendering.
type: application
version: 0.3.3
appVersion: "1.6.39"
keywords:
  - memcached
  - cache
  - in-memory
  - key-value
  - distributed
home: https://memcached.org
sources:
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/memcached
  - https://github.com/memcached/memcached
maintainers:
  - name: CloudPirates GmbH & Co. KG
    email: hello@cloudpirates.io
    url: https://www.cloudpirates.io
dependencies:
  - name: common
    version: "2.x.x"
    repository: oci://registry-1.docker.io/cloudpirates
icon: https://a.storyblok.com/f/143071/512x512/0faa83eb34/memcached-logo.svg
annotations:
  license: Apache-2.0
  artifacthub.io/category: database
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/signKey: |
    fingerprint: 6917f1a88c122cbb1de5aa55457752135bdcf95a
    url: https://raw.githubusercontent.com/CloudPirates-io/helm-charts/refs/heads/main/cosign.pub
  artifacthub.io/links: |
    - name: Memcached
      url: https://memcached.org
    - name: Helm Chart
      url: https://github.com/CloudPirates-io/helm-charts/tree/main/charts/memcached
    - name: Maintainer CloudPirates
      url: https://www.cloudpirates.io
  artifacthub.io/changes: |2
        - kind: changed
          description: "[memcached]: add missing automountServiceAccountToken key to deployment spec (#395)"
          links:
            - name: "Commit 93fee01"
              url: "https://github.com/CloudPirates-io/helm-charts/commit/93fee01"
