apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-headless
  namespace: {{ include "cloudpirates.namespace" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
    {{- if and .Values.sentinel.enabled (eq .Values.architecture "replication") }}
    - port: {{ .Values.sentinel.port }}
      targetPort: sentinel
      protocol: TCP
      name: sentinel
    {{- end }}
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}