apiVersion: v2
name: keycloak
description: Open Source Identity and Access Management Solution
type: application
version: 0.1.11
appVersion: "26.3.4"
keywords:
  - keycloak
  - identity
  - access-management
  - authentication
  - authorization
  - oauth
  - openid-connect
  - saml
home: https://www.cloudpirates.io
sources:
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/keycloak
maintainers:
  - name: CloudPirates GmbH & Co. KG
    url: https://www.cloudpirates.io
dependencies:
  - name: common
    version: "1.x.x"
    repository: oci://registry-1.docker.io/cloudpirates
  - name: postgres
    version: "0.x.x"
    repository: oci://registry-1.docker.io/cloudpirates
    condition: postgres.enabled
  - name: mariadb
    version: "0.x.x"
    repository: oci://registry-1.docker.io/cloudpirates
    condition: mariadb.enabled
icon: https://a.storyblok.com/f/143071/512x512/6a85e594b2/keycloak-logo.svg
