apiVersion: v2
name: keycloak
description: Open Source Identity and Access Management Solution
type: application
version: 0.7.0
appVersion: "26.4.2"
keywords:
  - keycloak
  - identity
  - access-management
  - authentication
  - authorization
  - oauth
  - openid-connect
  - saml
home: https://www.keycloak.org
sources:
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/keycloak
  - https://github.com/keycloak/keycloak
maintainers:
  - name: CloudPirates GmbH & Co. KG
    email: hello@cloudpirates.io
    url: https://www.cloudpirates.io
dependencies:
  - name: common
    version: "2.x.x"
    repository: oci://registry-1.docker.io/cloudpirates
  - name: postgres
    version: "0.9.x"
    repository: oci://registry-1.docker.io/cloudpirates
    condition: postgres.enabled
  - name: mariadb
    version: "0.4.x"
    repository: oci://registry-1.docker.io/cloudpirates
    condition: mariadb.enabled
icon: https://a.storyblok.com/f/143071/512x512/6a85e594b2/keycloak-logo.svg
annotations:
  license: Apache-2.0
  artifacthub.io/category: security
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/signKey: |
    fingerprint: 6917f1a88c122cbb1de5aa55457752135bdcf95a
    url: https://raw.githubusercontent.com/CloudPirates-io/helm-charts/refs/heads/main/cosign.pub
  artifacthub.io/links: |
    - name: Keycloak
      url: https://www.keycloak.org
    - name: Helm Chart
      url: https://github.com/CloudPirates-io/helm-charts/tree/main/charts/keycloak
    - name: Application
      url: https://github.com/keycloak/keycloak
    - name: Maintainer CloudPirates
      url: https://www.cloudpirates.io
  artifacthub.io/changes: |2
        - kind: changed
          description: "Chart updated"
