apiVersion: v2
name: mongodb
description: MongoDB a flexible NoSQL database for scalable, real-time data management
type: application
version: 0.5.3
appVersion: "8.0.15"
keywords:
  - mongodb
  - database
  - nosql
home: https://www.mongodb.com
sources:
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/mongodb
  - https://github.com/mongodb/mongo
maintainers:
  - name: CloudPirates GmbH & Co. KG
    email: hello@cloudpirates.io
    url: https://www.cloudpirates.io
dependencies:
  - name: common
    version: "2.x.x"
    repository: oci://registry-1.docker.io/cloudpirates
icon: https://a.storyblok.com/f/143071/512x512/5d228988dc/mongodb-logo.svg
annotations:
  license: Apache-2.0
  artifacthub.io/category: database
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/signKey: |
    fingerprint: 6917f1a88c122cbb1de5aa55457752135bdcf95a
    url: https://raw.githubusercontent.com/CloudPirates-io/helm-charts/refs/heads/main/cosign.pub
  artifacthub.io/links: |
    - name: MongoDB
      url: https://www.mongodb.com
    - name: Helm Chart
      url: https://github.com/CloudPirates-io/helm-charts/tree/main/charts/mongodb
    - name: Application
      url: https://github.com/mongodb/mongo
    - name: Maintainer CloudPirates
      url: https://www.cloudpirates.io
  artifacthub.io/changes: |2
        - kind: changed
          description: "Chart updated"
