apiVersion: v2
name: clusterpirate
description: Client agent for the CloudPirates Managed Observability Platform to connect your Kubernetes cluster to our infrastructure
type: application
version: 1.2.4
appVersion: "1.0.1"
keywords:
  - kubernetes
  - clusterpirate
  - cloudpirates
  - observability
  - agent
home: https://www.cloudpirates.io
sources:
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/clusterpirate
maintainers:
  - name: CloudPirates GmbH & Co. KG
    email: hello@cloudpirates.io
    url: https://www.cloudpirates.io
dependencies:
  - name: common
    version: "2.x.x"
    repository: oci://registry-1.docker.io/cloudpirates
  - name: valkey
    version: "0.6.2"
    repository: oci://registry-1.docker.io/cloudpirates
    condition: valkey.enabled
icon: https://a.storyblok.com/f/143071/512x512/88dc07809a/cluster-pirate-logo.svg
annotations:
  license: Apache-2.0
  artifacthub.io/category: monitoring-logging
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/signKey: |
    fingerprint: 6917f1a88c122cbb1de5aa55457752135bdcf95a
    url: https://raw.githubusercontent.com/CloudPirates-io/helm-charts/refs/heads/main/cosign.pub
  artifacthub.io/links: |
    - name: Helm Chart
      url: https://github.com/CloudPirates-io/helm-charts/tree/main/charts/clusterpirate
    - name: Maintainer CloudPirates
      url: https://www.cloudpirates.io
  artifacthub.io/changes: |2
        - kind: changed
          description: "Fix linting for values.yaml"
          links:
            - name: "Commit 504ac61"
              url: "https://github.com/dloewen2/helm-charts/commit/504ac61"
        - kind: changed
          description: "Fix values.yaml / Chart.yaml linting issues"
          links:
            - name: "Commit 043c7e0"
              url: "https://github.com/dloewen2/helm-charts/commit/043c7e0"
        - kind: changed
          description: "Add initial Changelogs to all Charts"
          links:
            - name: "Commit 68f10ca"
              url: "https://github.com/dloewen2/helm-charts/commit/68f10ca"
