apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rustfs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "rustfs.annotations" . | nindent 4 }}
  {{- end }}
data:
  RUSTFS_VOLUMES: {{ include "rustfs.volumes" . }}
  RUSTFS_ADDRESS: {{ .Values.config.address | quote }}
  RUSTFS_CONSOLE_ADDRESS: {{ .Values.config.consoleAddress | quote }}
  RUSTFS_CONSOLE_ENABLE: {{ .Values.config.consoleEnabled | quote }}
  RUSTFS_EXTERNAL_ADDRESS: {{ .Values.config.externalAddress | quote }}
  RUSTFS_CORS_ALLOWED_ORIGINS: {{ .Values.config.corsAllowedOrigins | quote }}
  RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS: {{ .Values.config.consoleCorsAllowedOrigins | quote }}
  RUSTFS_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  RUSTFS_TLS_PATH: {{ .Values.config.tlsPath | quote }}
  {{- range $key, $value := .Values.config.extraEnvVars }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}