apiVersion: v2
name: rabbitmq
description: A messaging broker that implements the Advanced Message Queuing Protocol (AMQP)
type: application
version: 0.5.4
appVersion: "4.1.4"
keywords:
  - rabbitmq
  - message broker
  - amqp
  - messaging
  - queue
home: https://www.rabbitmq.com
sources:
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/rabbitmq
  - https://github.com/rabbitmq/rabbitmq-server
maintainers:
  - name: CloudPirates GmbH & Co. KG
    email: hello@cloudpirates.io
    url: https://www.cloudpirates.io
dependencies:
  - name: common
    version: "2.x.x"
    repository: oci://registry-1.docker.io/cloudpirates
icon: https://a.storyblok.com/f/143071/512x512/aa1bd68288/rabbitmq-logo.svg
annotations:
  license: Apache-2.0
  artifacthub.io/category: streaming-messaging
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/signKey: |
    fingerprint: 6917f1a88c122cbb1de5aa55457752135bdcf95a
    url: https://raw.githubusercontent.com/CloudPirates-io/helm-charts/refs/heads/main/cosign.pub
  artifacthub.io/links: |
    - name: RabbitMQ
      url: https://www.rabbitmq.com
    - name: Helm Chart
      url: https://github.com/CloudPirates-io/helm-charts/tree/main/charts/rabbitmq
    - name: Application
      url: https://github.com/rabbitmq/rabbitmq-server
    - name: Maintainer CloudPirates
      url: https://www.cloudpirates.io
  artifacthub.io/changes: |2
        - kind: changed
          description: "Update charts/rabbitmq/values.yaml rabbitmq (#401)"
          links:
            - name: "Commit d364501"
              url: "https://github.com/CloudPirates-io/helm-charts/commit/d364501"
